<p><?php echo $_TP['text']; ?></p>
<p>Your Request Object:</p>
<p><?php var_dump($_TP['request']); ?></p>
<p>&nbsp;</p>
<p>You can also generate Urls by using the Urlbuilder class. It's available in every view, using $_URLBUILDER var.</p>
<p><a href="<?php echo $_URLBUILDER->buildUrl("index", "plus"); // indexController plusAction ?>">This link will lead to plusAction. Generated by Urlbuilder class inside the view.</a></p>